### ISSUE TITLE
Difference with DrupalDriver?

### ISSUE THREAD

**Issue by PieterDC** [weitzman/drupal-test-traits#1]
You seem to have an interesting approach with drupal-test-traits.

I haven't really dived in deep but can someone explain why/when one rather use this project (drupal-test-traits) than https://github.com/jhedstrom/DrupalDriver ?

Both allow to bootstrap Drupal within tests is what made me wonder.

**Comment by jhedstrom** [comment]
This seems a lot lighter-weight than the Driver. The background of that project was to allow tests to be written against multiple versions of Drupal (for instance, during a migration from 6 to 7), by providing a common API that things like the Behat Drupal Extension could rely on. Or similarly, use the same tests with different drivers (API, or drush, for instance).

In my experience, tests written using the driver tend to reside _outside_ or _alongside_ the drupal project (eg, in the case of Behat), while I'd envision using these traits in custom module tests (to replace the uses of Behat for this sort of full-functional testing of a site).

**Comment by PieterDC** [comment]
Thanks for that clarification! 

I couldn't have wished for someone better positioned to explain this - as you're the maintainer of DrupalDriver.
