### ISSUE TITLE
Warning in tests "THE ERROR HANDLER HAS CHANGED!"

### ISSUE THREAD

**Issue by benjy** [weitzman/drupal-test-traits#11]
**Describe the bug**
When running a functional test I get an error printed `THE ERROR HANDLER HAS CHANGED!`

The error comes from the phpunit-bridge, the code around the message is:

![screen shot 2018-05-14 at 4 43 46 pm](https://user-images.githubusercontent.com/863137/39987002-057c4d4a-5796-11e8-95fa-9df6a8e3e457.png)

Still looking into why this happens as i'm porting our tests from the core patch to these traits, if anyone has any clues let me know.

**Comment by weitzman** [comment]
Just want to encourage you to find the cause and to scold he developer in ALL CAPS. This message is obnoxious.

**Comment by benjy** [comment]
Because we call `DrupalKernel::createFromRequest()` in setUp we need to call `restore_error_handler();` in tearDown. We should probably also call $kernel->shutdown(). I'll create a PR later.

**Comment by weitzman** [comment]
FWIW we call restore_error_handler() immediately in Drush, not later like in a tearDown(). See https://github.com/drush-ops/drush/blob/master/src/Boot/DrupalBoot8.php#L177-L181

**Comment by weitzman** [comment]
I'm not seeing this anymore, with latest code and --bootstrap option as per latest README. Are you?

**Comment by jibran** [comment]
Nope, I'm still seeing the issue.

**Comment by benjy** [comment]
Still does it for me, calling restore_error_handler() immediately could be the right approach as we probably want the PHPUnit error handler to handle failing the test rather than the Drupal one logging errors in the test thread to watchdog.

**Comment by benjy** [comment]
Moving restore_error_handler() to setupDrupal() gives you all the depreciation notices in your test, I think that's the desired behaviour over having Drupal logging to watchdog during the test? They can be disabled with

    <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak_vendors"/>
