### ISSUE TITLE
Webdriver trait

### ISSUE THREAD

**Issue by jibran** [weitzman/drupal-test-traits#3]
We need a webdriver trait as well. :wink:

**Comment by weitzman** [comment]
Yes please. We should probably share code between it and the current MinkSetup. Details TBD.

**Comment by jibran** [comment]
How about using https://gitlab.com/DMore/chrome-mink-driver/ instead of PhantomJS and Selenium? OR we can provide trait for all of these.

**Comment by jibran** [comment]
Created #27 for this.

**Comment by weitzman** [comment]
Lets talk in the PR
