### ISSUE TITLE
Allow modification of the DI container in tests

### ISSUE THREAD

**Issue by weitzman** [weitzman/drupal-test-traits#31]
I received the following feature request. Would this be useful to others? Any ideas on how to implement it?

> It would be useful to be able to swap services in our test classes. Eg: instead of a normal mailer, we use a logging mailer. This might be implemented using the ServiceModifierInterface - https://www.drupal.org/docs/8/api/services-and-dependency-injection/altering-existing-services-providing-dynamic-services.

**Comment by rbayliss** [comment]
I'm imagining this could be implemented via an optional `getServiceModifiers()` method on the test class.  If there are service modifiers, we'd need to rebuild the container (or maybe core does that for us, not sure).  I think it would be useful for unlocking some really advanced behavior.

**Comment by jibran** [comment]
One can always include `settings.test.php` from the tests and then in that file, you can add services.test.yml using `$settings['container_yamls'][]` and in services.test.yml one can override any parameter or service definition.

**Comment by rbayliss** [comment]
Yeah, I think I'm the originator of this request initially, and @jibran's comment above is a good point - we have enough mechanisms for it already.
