### ISSUE TITLE
Autoloading for tests in ExistingSite namespace does not work with core's bootstrap.php

### ISSUE THREAD

**Issue by jhedstrom** [weitzman/drupal-test-traits#32]
**Describe the bug**
Using core's `bootstrap.php`, autoloading is not setup correctly for `foo/tests/src/ExistingSite` (and the corresponding JS one).

**To Reproduce**
* Add a base class that extends this project's base class, in module_a.
* In module_b, add a test that extends that class
* Note the base class in module_a is not found and the test fatal-errors.

**Expected behavior**
We need to provide an example bootstrap.php file that is capable of running the 2 new types of tests alongside the existing 4 core test types.

**Comment by weitzman** [comment]
Lets keep discussing in #33
