### ISSUE TITLE
Automatically mark created users, node, blocks etc for clean up

### ISSUE THREAD

**Issue by jibran** [weitzman/drupal-test-traits#6]
**Is your feature request related to a problem? Please describe.**
Over at [Allow BTB to test an existing, already installed Drupal site instead of installing from scratch](https://www.drupal.org/project/drupal/issues/2793445#comment-12608468), I suggested we should close the core feature request in favor of this but @benjy pointed out:
> Also, the traits in that project don't handle automatically marking created
users, node, blocks etc for clean up?

**Describe the solution you'd like**
Maybe provide a trait(s) to wrap `BlockCreationTrait`, `NodeCreationTrait`, `ContentTypeCreationTrait`, and `UserCreationTrait` and mark all the entities for clean up.

**Describe alternatives you've considered**
Maybe just provide a base class.

**Comment by weitzman** [comment]
Lets continue in #9
