### ISSUE TITLE
Allow debugging the remote request

### ISSUE THREAD

**Issue by jibran** [weitzman/drupal-test-traits#7]
**Is your feature request related to a problem? Please describe.**
BTB uses `XdebugRequestTrait` to allow debugging the test request.

**Describe the solution you'd like**
Maybe use the same `XdebugRequestTrait` here as well.

**Comment by weitzman** [comment]
I've been debugging with these traits without a problem. I guess I'll look at that Trait and see under what conditions its helpful.

I agree that debugging during tests is essential!

**Comment by weitzman** [comment]
Looks like we don't need anything special here since there is no child site with DTT. From XdebugTrait:

> If the developer listens to connection on the parent site, by
>  default the cookie is not forwarded to the client side, so you cannot
>  debug the code running on the child site.
